### ISSUE TITLE
Linux daemon run more cpu

### ISSUE THREAD

**Issue by netmebtc** [citicashio/citicash#2]
why linux daemon use more cpu?  There are many orphand blocks in many pools. maybe are cause by daemon run cpu overload.

![image](https://user-images.githubusercontent.com/32667839/46571050-da58c080-c9a0-11e8-85b5-4f904c0cc559.png)

**Comment by tr1st** [comment]
Hello, my daemon is absolutely OK. What CPU do you use?

<img width="997" alt="snimek obrazovky 2018-10-16 v 8 19 25" src="https://user-images.githubusercontent.com/8490837/46998269-59c55d00-d122-11e8-850a-7482a68b7ff6.png">

**Comment by netmebtc** [comment]
when call citicashd rpc ,cpu load will be high. if not call rpc ,it is normal

**Comment by tr1st** [comment]
I think so, please mark as solved.
