### ISSUE TITLE
wallet-rpc----]ERROR /root/citicash/src/wallet/wallet2.cpp:3836 outs.size() < out_index + 1. THROW EXCEPTION: error::wallet_internal_error

### ISSUE THREAD

**Issue by netmebtc** [citicashio/citicash#5]
![image](https://user-images.githubusercontent.com/32667839/47553231-13010f80-d939-11e8-8b02-18ce41737d09.png)

# ./citicash-wallet-rpc --version
Creating the logger system
Citicash 'Itynka' (v0.0.3.2-release)

# ./citicashd --version
Creating the logger system
Citicash 'Itynka' (v0.0.3.2-release)

**Comment by salda** [comment]
Fixed in afd3f6d7910ec3a68b3b4c222ff9e893bc4a73cc, will be in next release.

**Comment by salda** [comment]
test 367f7ff88647c91e027050a36d551bec749c2685
